### ISSUE TITLE
RET model is missing

### ISSUE THREAD

**Issue by ktrk115** [yj-yu/lsmdc#1]
Hi. Thank you for providing code.
I would like to reproduce the results of movie retrieval, but I cannot find RET model in this refreshed repository.
Why was it deleted? And will it be uploaded?

**Comment by yj-yu** [comment]
Yes, we'll update later with preprocessed feature and checkpoints.

**Comment by sreyashi-nag** [comment]
Hi,
Could you let us know an approximate time by when the preprocessed features and checkpoints will be made available?
Thanks!

**Comment by yj-yu** [comment]
Will update soon! within 1~2 week,, sorry for late, we don't have additional GPU resource to make checkpoint right now :( and we found minor error in refactored code! thanks
